name: Build and deploy on merge

on:
  push:
    branches: [ master ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          # with:
          #   creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: benchmarkregistry
            # username: ${{ secrets.REGISTRY_USERNAME }}
            # password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t benchmarkregistry.azurecr.io/benchmark:prod
            docker push benchmarkregistry.azurecr.io/benchmark:prod