name: Test on PR

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents:
    read

env:
  SQLALCHEMY_DATABASE_URL: sqlite:///

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run pre-commit run --all-files
    # - name: Test with pytest
    #   run: |
    #     poetry run pytest tests
